<section class="ftco-section">
    <div class="container">
        <div class="row">
            <?php foreach ($params['dishTypes'] as $dishType) : ?>
            <div class="col-md-12">
                <div class="row mb-4 border-bottom border-dark">
                    <div class="d-flex">
                        <div class="desc pl-3">
                            <div class="d-flex text align-items-center">
                                <h3>
                                    <?= $dishType['name'] ?>
                                </h3>
                            </div>
                            <a href="/admin/tipus-szerkesztese?id=<?= $dishType['id'] ?>">
                                <button class="btn btn-sm btn-outline-warning">Szerkesztés</button>
                            </a>
                            <form action="/delete-type?id=<?= $dishType['id'] ?>" method="POST" class="d-inline-block">
                                <button class="btn btn-sm btn-outline-danger">Törlés</button>
                            </form>

                        </div>

                    </div>

                </div>
            </div>
            <?php endforeach ?>
        </div>

        <div class="col-md-12 mb-5 pb-3">
            <h3>Új ételtípus létrehozása</h3>
            <form action="/create-dish-type" method="POST">
                <div class="form-group row">
                    <label for="inputName" class="col-sm-2 col-form-label">Név</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" name="name">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                            name="description"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Elküldés</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>