<section class="ftco-section pt-3">
    <div class="container">

        <div class="col-md-12 mb-5 pb-3">
            <h3>
                <?= $params['type']['name'] ?> szerkesztése
            </h3>
            <form action="/update-type?id=<?= $params['type']['id'] ?>" method="POST">
                <div class="form-group row">
                    <label for="inputName" class="col-sm-2 col-form-label">Név</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputName" name="name"
                            value="<?= $params['type']['name'] ?> ">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Leírás</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"
                            name="description"><?= $params['type']['description'] ?>                        </textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Elküldés</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>